# 指定がない場合のデフォルト
spring:
  profiles:
    active: dev


# spring actuator config
management:
  server:
    port: 9999
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: auditevents,beans,health,env,metrics,mappings,configprops,scheduledtasks

