# 指定がない場合のデフォルト
spring:
  profiles:
    active: dev

server:
  port: 8888

# spring actuator config
management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: beans,health,env,metrics,mappings,configprops
#        include: auditevents,beans,health,env,metrics,mappings,configprops,scheduledtasks


ipatgo:
  authentication:
    INetId: XXXXXXX
    subscriberNo: XXXXXX
    password: XXXXXX
    parsNo: XXXXX

