setup:
  yyyyMMddHHmmss: 2019/01/01 00:00:00
  dataTypes:
    RacingDetails,
    HorseRacingDetails,
    RaceRefund,
    VoteCount,
    Ancestry,
    BreedingHorse,
    Offspring,
    Course,
    RaceHorse,
    Jockey,
    Trainer,
    Owner,
    Breeder
